export const strings = {
  en: {
    appName: 'PolicyBot',
    tagline: 'Making government policies accessible',
    home: 'Home',
    policies: 'Policies',
    chat: 'Chat',
    compare: 'Compare',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    searchPlaceholder: 'Search policies, schemes, laws...',
    noResults: 'No policies found',
    readMore: 'Read More',
    bookmark: 'Bookmark',
    bookmarked: 'Bookmarked',
    explainAI: 'Explain Simply',
    share: 'Share',
    generateFAQ: 'Generate FAQs',
    comparePolicies: 'Compare Policies',
    uploadPDF: 'Upload PDF',
    voiceInput: 'Voice Input',
    sendMessage: 'Send',
    newChat: 'New Chat',
    chatPlaceholder: 'Ask about any government policy...',
    aiTyping: 'NyayaBot is typing...',
    welcomeMessage: 'Hello! I am NyayaBot. Ask me anything about government policies.',
    loading: 'Loading...',
    error: 'Something went wrong',
    tryAgain: 'Try Again',
    categories: 'Categories',
    allCategories: 'All Categories',
    showingResults: 'Showing {count} results',
    sortBy: 'Sort By',
    newest: 'Newest First',
    mostViewed: 'Most Viewed',
    adminDashboard: 'Admin Dashboard',
    totalUsers: 'Total Users',
    totalPolicies: 'Total Policies',
    totalChats: 'Total Chats',
    feedback: 'Feedback',
    rating: 'Rating',
    submitFeedback: 'Submit Feedback',
    feedbackThanks: 'Thank you for your feedback!',
    heroTitle: 'Understand Indian Policies',
    heroHighlight: 'Without the Legal Jargon.',
    heroSubtitle: 'Our AI-powered assistant breaks down complex government laws and schemes into simple, plain language for every citizen.',
    startChatting: 'Start Chatting',
    browsePolicies: 'Browse Policies',
    empoweringTitle: 'Empowering Citizens with Knowledge',
    empoweringDesc: 'Join thousands of users who are making better informed decisions by understanding their rights and benefits.',
    explorePolicies: 'Explore Policies',
    getStartedFree: 'Get Started for Free',
    compareTitle: 'Compare Policies',
    compareDesc: 'Select two policies to see a side-by-side AI comparison.',
    policy1: 'Policy 1',
    policy2: 'Policy 2',
    selectPolicy: 'Select a policy...',
    compareWithAI: 'Compare with AI',
    analyzingComparison: 'Analyzing Comparison...',
    aiComparativeAnalysis: 'AI Comparative Analysis'
  },
  hi: {
    appName: 'पॉलिसीबॉट',
    tagline: 'सरकारी नीतियों को सुलभ बनाना',
    home: 'होम',
    policies: 'नीतियां',
    chat: 'चैट',
    compare: 'तुलना करें',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    logout: 'लॉगआउट',
    dashboard: 'डैशबोर्ड',
    searchPlaceholder: 'नीतियां, योजनाएं खोजें...',
    noResults: 'कोई नीति नहीं मिली',
    readMore: 'और पढ़ें',
    bookmark: 'बुकमार्क',
    bookmarked: 'बुकमार्क किया',
    explainAI: 'आसानी से समझाएं',
    share: 'साझा करें',
    generateFAQ: 'सवाल-जवाब बनाएं',
    comparePolicies: 'नीतियों की तुलना करें',
    uploadPDF: 'PDF अपलोड करें',
    voiceInput: 'आवाज से पूछें',
    sendMessage: 'भेजें',
    newChat: 'नई चैट',
    chatPlaceholder: 'कोई भी सरकारी नीति पूछें...',
    aiTyping: 'NyayaBot लिख रहा है...',
    welcomeMessage: 'नमस्ते! मैं NyayaBot हूं। सरकारी नीतियों के बारे में कुछ भी पूछें।',
    loading: 'लोड हो रहा है...',
    error: 'कुछ गलत हो गया',
    tryAgain: 'फिर कोशिश करें',
    categories: 'श्रेणियां',
    allCategories: 'सभी श्रेणियां',
    showingResults: '{count} परिणाम दिख रहे हैं',
    sortBy: 'क्रमबद्ध करें',
    newest: 'नवीनतम पहले',
    mostViewed: 'सबसे अधिक देखे गए',
    adminDashboard: 'एडमिन डैशबोर्ड',
    totalUsers: 'कुल उपयोगकर्ता',
    totalPolicies: 'कुल नीतियां',
    totalChats: 'कुल चैट',
    feedback: 'प्रतिक्रिया',
    rating: 'रेटिंग',
    submitFeedback: 'प्रतिक्रिया भेजें',
    feedbackThanks: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    heroTitle: 'भारतीय नीतियों को समझें',
    heroHighlight: 'बिना किसी कानूनी उलझन के।',
    heroSubtitle: 'हमारा एआई-पावर्ड असिस्टेंट जटिल सरकारी कानूनों और योजनाओं को हर नागरिक के लिए सरल, आम भाषा में समझाता है।',
    startChatting: 'चैट शुरू करें',
    browsePolicies: 'नीतियां ब्राउज़ करें',
    empoweringTitle: 'ज्ञान के साथ नागरिकों को सशक्त बनाना',
    empoweringDesc: 'उन हजारों उपयोगकर्ताओं में शामिल हों जो अपने अधिकारों और लाभों को समझकर बेहतर निर्णय ले रहे हैं।',
    explorePolicies: 'नीतियां खोजें',
    getStartedFree: 'मुफ्त में शुरू करें',
    compareTitle: 'नीतियों की तुलना करें',
    compareDesc: 'साइड-बाय-साइड एआई तुलना देखने के लिए दो नीतियों का चयन करें।',
    policy1: 'नीति 1',
    policy2: 'नीति 2',
    selectPolicy: 'एक नीति चुनें...',
    compareWithAI: 'एआई के साथ तुलना करें',
    analyzingComparison: 'तुलना का विश्लेषण हो रहा है...',
    aiComparativeAnalysis: 'एआई तुलनात्मक विश्लेषण'
  },
  kn: {
    appName: 'ಪಾಲಿಸಿಬಾಟ್',
    tagline: 'ಸರ್ಕಾರಿ ನೀತಿಗಳನ್ನು ಸರಳಗೊಳಿಸುತ್ತಿದೆ',
    home: 'ಮನೆ',
    policies: 'ನೀತಿಗಳು',
    chat: 'ಚಾಟ್',
    compare: 'ಹೋಲಿಕೆ',
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    logout: 'ಲಾಗ್ ಔಟ್',
    dashboard: 'ಡ್ಯಾಶ್ಬೋರ್ಡ್',
    searchPlaceholder: 'ನೀತಿಗಳು, ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...',
    noResults: 'ಯಾವುದೇ ನೀತಿ ಕಂಡುಬಂದಿಲ್ಲ',
    readMore: 'ಮತ್ತಷ್ಟು ಓದಿ',
    bookmark: 'ಬುಕ್ಮಾರ್ಕ್',
    bookmarked: 'ಬುಕ್ಮಾರ್ಕ್ ಆಗಿದೆ',
    explainAI: 'ಸರಳಗೊಳಿಸಿ',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    generateFAQ: 'FAQ ರಚಿಸಿ',
    comparePolicies: 'ನೀತಿಗಳನ್ನು ಹೋಲಿಸಿ',
    uploadPDF: 'PDF ಅಪ್ಲೋಡ್',
    voiceInput: 'ಧ್ವನಿ ಇನ್ಪುಟ್',
    sendMessage: 'ಕಳುಹಿಸಿ',
    newChat: 'ಹೊಸ ಚಾಟ್',
    chatPlaceholder: 'ಯಾವುದೇ ಸರ್ಕಾರಿ ನೀತಿ ಕೇಳಿ...',
    aiTyping: 'NyayaBot ಟೈಪ್ ಮಾಡುತ್ತಿದೆ...',
    welcomeMessage: 'ನಮಸ್ಕಾರ! ನಾನು NyayaBot. ಸರ್ಕಾರಿ ನೀತಿಗಳ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ.',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    error: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    tryAgain: 'ಮತ್ತೆ प्रयत्नಿಸಿ',
    categories: 'ವರ್ಗಗಳು',
    allCategories: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    showingResults: '{count} ಫಲಿತಾಂಶಗಳು',
    sortBy: 'ವಿಂಗಡಿಸಿ',
    newest: 'ಹೊಸದು ಮೊದಲು',
    mostViewed: 'ಹೆಚ್ಚು ವೀಕ್ಷಿಸಲಾಗಿದೆ',
    adminDashboard: 'ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್ಬೋರ್ಡ್',
    totalUsers: 'ಒಟ್ಟು ಬಳಕೆದಾರರು',
    totalPolicies: 'ಒಟ್ಟು ನೀತಿಗಳು',
    totalChats: 'ಒಟ್ಟು ಚಾಟ್ಗಳು',
    feedback: 'ಪ್ರತಿಕ್ರಿಯೆ',
    rating: 'ರೇಟಿಂಗ್',
    submitFeedback: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
    feedbackThanks: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!',
    heroTitle: 'ಭಾರತೀಯ ನೀತಿಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ',
    heroHighlight: 'ಕಾನೂನು ತೊಡಕುಗಳಿಲ್ಲದೆ.',
    heroSubtitle: 'ನಮ್ಮ ಎಐ ಆಧಾರಿತ ಸಹಾಯಕ ಸಂಕೀರ್ಣ ಸರ್ಕಾರಿ ಕಾನೂನುಗಳು ಮತ್ತು ಯೋಜನೆಗಳನ್ನು ಪ್ರತಿ ಪ್ರಜೆಗೆ ಸರಳ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸುತ್ತಾನೆ.',
    startChatting: 'ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ',
    browsePolicies: 'ನೀತಿಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    empoweringTitle: 'ಜ್ಞಾನದಿಂದ ಪ್ರಜೆಗಳನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು',
    empoweringDesc: 'ತಮ್ಮ ಹಕ್ಕುಗಳು ಮತ್ತು ಪ್ರಯೋಜನಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವ ಮೂಲಕ ಉತ್ತಮ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತಿರುವ ಸಾವಿರಾರು ಬಳಕೆದಾರರನ್ನು ಸೇರಿ.',
    explorePolicies: 'ನೀತಿಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    getStartedFree: 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    compareTitle: 'ನೀತಿಗಳನ್ನು ಹೋಲಿಸಿ',
    compareDesc: 'ಎಐ ಮೂಲಕ ಅಕ್ಕಪಕ್ಕದ ಹೋಲಿಕೆಯನ್ನು ನೋಡಲು ಎರಡು ನೀತಿಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    policy1: 'ನೀತಿ 1',
    policy2: 'ನೀತಿ 2',
    selectPolicy: 'ಒಂದು ನೀತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ...',
    compareWithAI: 'ಎಐನೊಂದಿಗೆ ಹೋಲಿಸಿ',
    analyzingComparison: 'ಹೋಲಿಕೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    aiComparativeAnalysis: 'ಎಐ ತುಲನಾತ್ಮಕ ವಿಶ್ಲೇಷಣೆ'
  },
  ta: {
    appName: 'பாலிசிபாட்',
    tagline: 'அரசு கொள்கைகளை எளிதாக்குகிறோம்',
    home: 'முகப்பு',
    policies: 'கொள்கைகள்',
    chat: 'அரட்டை',
    compare: 'ஒப்பிடு',
    login: 'உள்நுழைவு',
    register: 'பதிவு',
    logout: 'வெளியேறு',
    dashboard: 'டாஷ்போர்டு',
    searchPlaceholder: 'கொள்கைகள், திட்டங்களை தேடுங்கள்...',
    noResults: 'கொள்கைகள் எதுவும் கிடைக்கவில்லை',
    readMore: 'மேலும் படிக்க',
    bookmark: 'புக்மார்க்',
    bookmarked: 'புக்மார்க் செய்யப்பட்டது',
    explainAI: 'எளிமையாக விளக்கு',
    share: 'பகிர்',
    generateFAQ: 'கேள்விகள் உருவாக்கு',
    comparePolicies: 'கொள்கைகளை ஒப்பிடு',
    uploadPDF: 'PDF பதிவேற்றம்',
    voiceInput: 'குரல் உள்ளீடு',
    sendMessage: 'அனுப்பு',
    newChat: 'புதிய அரட்டை',
    chatPlaceholder: 'எந்த அரசு கொள்கையையும் கேளுங்கள்...',
    aiTyping: 'NyayaBot தட்டச்சு செய்கிறது...',
    welcomeMessage: 'வணக்கம்! நான் NyayaBot. அரசு கொள்கைகளைப் பற்றி எதுவும் கேளுங்கள்.',
    loading: 'ஏற்றுகிறது...',
    error: 'ஏதோ தவறாகிவிட்டது',
    tryAgain: 'மீண்டும் முயற்சிக்கவும்',
    categories: 'வகைகள்',
    allCategories: 'அனைத்து வகைகள்',
    showingResults: '{count} முடிவுகள்',
    sortBy: 'வரிசைப்படுத்து',
    newest: 'புதியது முதலில்',
    mostViewed: 'அதிகம் பார்க்கப்பட்டது',
    adminDashboard: 'நிர்வாக டாஷ்போர்டு',
    totalUsers: 'மொத்த பயனர்கள்',
    totalPolicies: 'மொத்த கொள்கைகள்',
    totalChats: 'மொத்த அரட்டைகள்',
    feedback: 'கருத்து',
    rating: 'மதிப்பீடு',
    submitFeedback: 'கருத்தை சமர்ப்பிக்கவும்',
    feedbackThanks: 'உங்கள் கருத்துக்கு நன்றி!',
    heroTitle: 'இந்தியக் கொள்கைகளைப் புரிந்து கொள்ளுங்கள்',
    heroHighlight: 'சட்டச் சிக்கல்கள் இல்லாமல்.',
    heroSubtitle: 'எங்கள் ஏஐ உதவியாளர் சிக்கலான அரசு சட்டங்கள் மற்றும் திட்டங்களை ஒவ்வொரு குடிமகனுக்கும் எளிய மொழியில் விளக்குகிறது.',
    startChatting: 'உரையாடலைத் தொடங்கு',
    browsePolicies: 'கொள்கைகளை உலாவு',
    empoweringTitle: 'அறிவின் மூலம் குடிமக்களுக்கு அதிகாரம் அளித்தல்',
    empoweringDesc: 'தங்கள் உரிமைகள் மற்றும் நன்மைகளைப் புரிந்து கொண்டு சிறந்த முடிவுகளை எடுக்கும் ஆயிரக்கணக்கான பயனர்களுடன் சேருங்கள்.',
    explorePolicies: 'கொள்கைகளை ஆராயுங்கள்',
    getStartedFree: 'இலவசமாகத் தொடங்குங்கள்',
    compareTitle: 'கொள்கைகளை ஒப்பிடு',
    compareDesc: 'பக்கவாட்டு ஏஐ ஒப்பீட்டைக் காண இரண்டு கொள்கைகளைத் தேர்ந்தெடுக்கவும்.',
    policy1: 'கொள்கை 1',
    policy2: 'கொள்கை 2',
    selectPolicy: 'ஒரு கொள்கையைத் தேர்ந்தெடுக்கவும்...',
    compareWithAI: 'ஏஐ உடன் ஒப்பிடு',
    analyzingComparison: 'ஒப்பீட்டை பகுப்பாய்வு செய்கிறது...',
    aiComparativeAnalysis: 'ஏஐ ஒப்பீட்டு பகுப்பாய்வு'
  }
};

export const t = (key, lang = 'en', vars = {}) => {
  let text = strings[lang]?.[key] || strings.en[key] || key;
  Object.keys(vars).forEach(v => {
    text = text.replace(`{${v}}`, vars[v]);
  });
  return text;
};
